In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix

In [ ]:
data=pd.read_csv("/content/sample_data/restaurant_reviews.csv")
print("Dataset Shape:",data.shape)
print("Columns:",data.columns)

Dataset Shape: (110, 19)
Columns: Index(['Restaurant', 'Review', 'Real', 'Reviewer', 'F1-AWL', 'F2-PAU',
       'F3-ANP', 'F4-ASL', 'F5-NCL', 'F6-NWO', 'F7-NVB', 'F8-NAJ', 'F9-NPV',
       'F10-EMO', 'F11-CDV', 'F12-RED', 'F13-LXD', 'F14-NMV', 'F15-NTY'],
      dtype='object')

In [ ]:
data.describe()

,Real,Reviewer,F1-AWL,F2-PAU,F3-ANP,F4-ASL,F5-NCL,F6-NWO,F7-NVB,F8-NAJ,F9-NPV,F10-EMO,F11-CDV,F12-RED,F13-LXD,F14-NMV,F15-NTY
count,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000
mean,0.500000,1.200000,3.857504,1.460031,10.320389,14.678680,6.009091,85.554545,8.872727,7.818182,0.181818,0.679627,0.893684,7.747949,0.774022,0.654545,0.300000
std,0.502288,1.412916,0.304887,0.619943,4.162323,5.337603,2.790861,45.851693,5.878134,5.477530,0.432230,0.309591,0.073120,3.349593,0.084147,0.923062,0.710988
min,0.000000,0.000000,2.916667,0.500000,0.000000,6.600000,1.000000,12.000000,0.000000,0.000000,0.000000,0.076923,0.675676,1.000000,0.575758,0.000000,0.000000
25%,0.000000,0.000000,3.611620,1.000000,8.000000,11.270833,4.000000,57.250000,5.000000,5.000000,0.000000,0.455492,0.833333,5.525000,0.712616,0.000000,0.000000
50%,0.500000,0.500000,3.846056,1.267857,9.766667,14.207143,5.000000,78.000000,7.500000,7.000000,0.000000,0.633399,0.890097,7.250000,0.770456,0.000000,0.000000
75%,1.000000,2.000000,4.047615,1.571429,11.225000,17.187500,7.000000,97.500000,11.000000,9.000000,0.000000,0.796429,0.957386,9.458333,0.814501,1.000000,0.000000
max,1.000000,4.000000,5.031250,4.000000,38.500000,43.600000,15.000000,271.000000,32.000000,40.000000,2.000000,1.666667,1.000000,24.200000,1.000000,4.000000,4.000000

In [ ]:
data.head()

,Restaurant,Review,Real,Reviewer,F1-AWL,F2-PAU,F3-ANP,F4-ASL,F5-NCL,F6-NWO,F7-NVB,F8-NAJ,F9-NPV,F10-EMO,F11-CDV,F12-RED,F13-LXD,F14-NMV,F15-NTY
0,Rose Restaurant,Great food and great atmosphere! The chicken t...,0,3,4.465909,1.000000,14.250000,17.600000,5,88,9,6,0,0.636364,0.972973,9.200000,0.795181,0,0
1,Rose Restaurant,I had heard good things about Rose Restaurant ...,0,3,3.838983,1.500000,10.000000,19.666667,6,118,17,8,1,0.545455,0.976190,11.166667,0.752294,0,0
2,Rose Restaurant,I was driving by rose restaurant one day and d...,0,3,3.377049,1.142857,8.923077,17.428571,7,122,14,5,1,0.375000,0.864865,11.000000,0.675439,0,0
3,Rose Restaurant,Rose Restaurant had the most modern and up-to-...,0,3,4.044118,1.750000,17.500000,17.000000,4,68,6,7,0,0.578947,0.961538,8.750000,0.819672,0,0
4,Gloria Restaurant,Today is the third time I've come to Gloria Re...,0,3,4.071429,1.500000,10.700000,14.000000,6,84,8,8,0,0.777778,0.937500,7.166667,0.786667,0,0

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 19 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Restaurant  110 non-null    object
 1   Review      110 non-null    object
 2   Real        110 non-null    int64
 3   Reviewer    110 non-null    int64
 4   F1-AWL      110 non-null    float64
 5   F2-PAU      110 non-null    float64
 6   F3-ANP      110 non-null    float64
 7   F4-ASL      110 non-null    float64
 8   F5-NCL      110 non-null    int64
 9   F6-NWO      110 non-null    int64
 10  F7-NVB      110 non-null    int64
 11  F8-NAJ      110 non-null    int64
 12  F9-NPV      110 non-null    int64
 13  F10-EMO     110 non-null    float64
 14  F11-CDV     110 non-null    float64
 15  F12-RED     110 non-null    float64
 16  F13-LXD     110 non-null    float64
 17  F14-NMV     110 non-null    int64
 18  F15-NTY     110 non-null    int64
dtypes: float64(8), int64(9), object(2)
memory usage: 16.5+ KB

In [ ]:
data.isnull().sum()

Restaurant    0
Review        0
Real          0
Reviewer      0
F1-AWL        0
F2-PAU        0
F3-ANP        0
F4-ASL        0
F5-NCL        0
F6-NWO        0
F7-NVB        0
F8-NAJ        0
F9-NPV        0
F10-EMO       0
F11-CDV       0
F12-RED       0
F13-LXD       0
F14-NMV       0
F15-NTY       0
dtype: int64

In [ ]:
y=data["Real"]
x=data.drop(columns=["Real"])
feature_cols=[col for col in data.columns if col.startswith("F")]

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)

In [ ]:
preprocessor=ColumnTransformer(transformers=[
    ("text",TfidfVectorizer(stop_words='english'),'Review'),
     ("num",StandardScaler(),feature_cols)
])

In [ ]:
svm_model=Pipeline([
    ("preprocessor",preprocessor),
    ("classifier",LinearSVC(class_weight="balanced"))
])

In [ ]:
svm_model.fit(x_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('text',
                                                  TfidfVectorizer(stop_words='english'),
                                                  'Review'),
                                                 ('num', StandardScaler(),
                                                  ['F1-AWL', 'F2-PAU', 'F3-ANP',
                                                   'F4-ASL', 'F5-NCL', 'F6-NWO',
                                                   'F7-NVB', 'F8-NAJ', 'F9-NPV',
                                                   'F10-EMO', 'F11-CDV',
                                                   'F12-RED', 'F13-LXD',
                                                   'F14-NMV', 'F15-NTY'])])),
                ('classifier', LinearSVC(class_weight='balanced'))])

In [ ]:
y_pred=svm_model.predict(x_test)
print("Accuracy:\n",accuracy_score(y_test,y_pred))
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred))
print("Classification Report:\n",classification_report(y_test,y_pred))

Accuracy:
 0.8636363636363636
Confusion Matrix:
 [[ 9  2]
 [ 1 10]]
Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.82      0.86        11
           1       0.83      0.91      0.87        11

    accuracy                           0.86        22
   macro avg       0.87      0.86      0.86        22
weighted avg       0.87      0.86      0.86        22

In [ ]:
x=data['Review']
y=data['Real']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)
model=Pipeline([
    ('tfidf',TfidfVectorizer(stop_words='english')),
    ('classifier',LinearSVC(class_weight='balanced'))
])
model.fit(x_train,y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer(stop_words='english')),
                ('classifier', LinearSVC(class_weight='balanced'))])

In [ ]:
def check_review(text):
  prediction=model.predict([text])
  if prediction[0]==1:
    print("Real Review")
  else:
    print("Fake Review")

check_review("This place is not good")
check_review("Great food and great atmosphere!")

Fake Review
Real Review